# Generated by Django 3.1.7 on 2021-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210416_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='password1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='signin',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
