# Generated by Django 3.1.7 on 2021-04-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210416_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='secondname',
        ),
    ]
