# Generated by Django 3.1.7 on 2021-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_signin_secondname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signin',
        ),
    ]
