# Generated by Django 3.1.7 on 2021-05-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
