# Generated by Django 3.1.7 on 2021-06-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210602_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
