# Generated by Django 3.1.7 on 2021-06-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartitem_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cartitem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
